name: Build for Windows
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout 🛒
        uses: actions/checkout@v2.3.1

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.5

      - run: |
          mkdir "%HAXELIB_ROOT%"
          haxelib setup "%HAXELIB_ROOT%"
          
      - name: Install Libraries
        run: |
          haxelib install lime 7.9.0
          haxelib install openfl
          haxelib install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib install hscript
          haxelib install newgrounds
          haxelib install linc_luajit
          haxelib git faxe https://github.com/uhrobots/faxe
          haxelib git polymod https://github.com/larsiusprime/polymod.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib install actuate
          haxelib git extension-webm https://github.com/KadeDev/extension-webm
          lime rebuild extension-webm windows
          RefreshEnv

      - name: Build Windows debug version
        run: |
          haxelib run lime build windows -debug

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: AikoyoriGamingMixes
          path: export/debug/windows/bin